// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAtY0M8lQ-l9o_ldRWtmveYlI4fxt4YLY',
    appId: '1:639256961120:web:6b290629eed6d7653a6305',
    messagingSenderId: '639256961120',
    projectId: 'com-healthconsultant-doctor',
    authDomain: 'com-healthconsultant-doctor.firebaseapp.com',
    storageBucket: 'com-healthconsultant-doctor.firebasestorage.app',
    measurementId: 'G-2F1S5P3877',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDysJ7mdKFOcHgtXwHRlhRt_YxIfWMDU1E',
    appId: '1:639256961120:android:878d1482a10596df3a6305',
    messagingSenderId: '639256961120',
    projectId: 'com-healthconsultant-doctor',
    storageBucket: 'com-healthconsultant-doctor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeAzwckNrAzWS8SqIyt769_HICo4SJE2Q',
    appId: '1:639256961120:ios:81573043883bfcd73a6305',
    messagingSenderId: '639256961120',
    projectId: 'com-healthconsultant-doctor',
    storageBucket: 'com-healthconsultant-doctor.firebasestorage.app',
    iosBundleId: 'com.example.healthConsultantForDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeAzwckNrAzWS8SqIyt769_HICo4SJE2Q',
    appId: '1:639256961120:ios:81573043883bfcd73a6305',
    messagingSenderId: '639256961120',
    projectId: 'com-healthconsultant-doctor',
    storageBucket: 'com-healthconsultant-doctor.firebasestorage.app',
    iosBundleId: 'com.example.healthConsultantForDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAtY0M8lQ-l9o_ldRWtmveYlI4fxt4YLY',
    appId: '1:639256961120:web:74c74d18f5827cc43a6305',
    messagingSenderId: '639256961120',
    projectId: 'com-healthconsultant-doctor',
    authDomain: 'com-healthconsultant-doctor.firebaseapp.com',
    storageBucket: 'com-healthconsultant-doctor.firebasestorage.app',
    measurementId: 'G-MRESCHQ9TN',
  );
}
